### ISSUE TITLE
$Prereqs3Folder is used for downloading SilverLight and Not Defined

### ISSUE THREAD

**Issue by NPrice99** [DanHolme/SP2016-Prereq-Downloader#1]
Hi Dan

Just used your script to download the Prequisites and I noticed that you use $PreReqs3Folder to down load Silver Light.  But $PreReqs3Folder is not defined in the Configuration block.  So Silverlight downloads in C:\ .

Regards

Nigel

**Comment by DanHolme** [comment]
Thanks for the note, Nigel! A victim of last-minute "simplification"... Fixed!
